# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
stages:
    - stage: 'build'
      jobs: 
      - job: 'build'
        pool:
         vmImage: 'ubuntu-latest'
         steps:
         - task: NuGetToolInstaller@1
           inputs:
             versionSpec: 
             - task: NuGetCommand@2
               inputs:
                 command: 'restore'
                 restoreSolution: '**/*.sln'
                 feedsToUse: 'select'
             - task: VSBuild@1
               inputs:
                  solution: '**\*.sln'
             - task: CopyFiles@2
               inputs:
                  SourceFolder: '$(Build.SourcesDirectory)'
                  Contents: '**'
                  TargetFolder: '$(build.artifactstagingdirectory)'
             - task: PublishBuildArtifacts@1
               inputs:
                  PathtoPublish: '$(Build.ArtifactStagingDirectory)'
                  ArtifactName: 'drop'
                  publishLocation: 'Container'

    # # Release pipeline 
    # - stage: Deploy
    #   dependsOn: Build
    #   condition: succeeded()
    #   jobs:
    #   - job: 
    #     pool: 
    #       vmImage: ubuntu-latest
    #       steps:
    #       - task: DownloadBuildArtifacts@1
    #         inputs:
    #           buildType: 'current'
    #           downloadType: 'single'
    #           artifactName: 'drop'
    #           downloadPath: '$(System.ArtifactsDirectory)'
    #       - task: AzureRmWebAppDeployment@4
    #         inputs:
    #           ConnectionType: 'AzureRM'
    #           azureSubscription: 'Devops-AgoraWebApp-Dev-SC-Agora-Platform-OPT_Demo_Project'
    #           appType: 'webAppLinux'
    #           WebAppName: 'devops-yamlDemo-webapp'
    #           packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

