# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Author: madhu
# https://aka.ms/yaml

trigger:
- none
stages:

- stage: 'Build'
  jobs:
  - job: 
    pool:
     vmImage: ubuntu-latest
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '6.6.1'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'WebApplication1/WebApplication1.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'WebApplication1/WebApplication1.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: 'Deploy'
  dependsOn: 'Build'
  condition: succeeded()
  jobs:
  - job: 
    pool: 
     vmImage: ubuntu-latest  
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Devops-AgoraWebApp-Dev-SC-Agora-Platform-OPT_Demo_Project'
        appType: 'webAppLinux'
        WebAppName: 'devops-yamlDemo-webapp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
- stage: 'publish'
dependsOn: 'Deploy'
  condition: succeeded()
  jobs:
  - job: 
    pool: 
     vmImage: ubuntu-latest  
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Devops-AgoraWebApp-Dev-SC-Agora-Platform-OPT_Demo_Project'
        appType: 'webAppLinux'
        WebAppName: 'devops-yamlDemo-webapp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'



